// Report-only diff between wh11ed's faction data and wh40k-appdata (the private sibling
// repo treated as the 100%-authoritative rules source — a dump of the official GW app).
//
// Usage:
//   node scripts/sync-appdata.mjs <slug> [<slug> ...]
//   node scripts/sync-appdata.mjs --all
//
// For each wh11ed faction slug, resolves the matching wh40k-appdata faction bundle (see
// SLUG_MAP below — a few names differ, e.g. wh11ed's space-marines.js is appdata's
// "adeptus-astartes"), and reports what appdata has that wh11ed doesn't (candidates to
// add — this is how the missing Battle Round 09.05.01 section and 28 missing FAQs were
// found), what wh11ed has that appdata doesn't (rename/Legends/removed candidates), and
// scalar mismatches (stratagem CP, enhancement/datasheet points) for anything matched.
//
// Matching is by normalized NAME, not id — wh11ed doesn't carry appdata's ids yet
// (`sourceId`, see CLAUDE.md). This script only reads and reports; nothing is written to
// data files. A future --write mode can use this same name-matching to backfill sourceId
// for id-based matching on every later run.
//
// Scope: this script reports structural presence/absence and scalar fields (cp/cost/points)
// only. Rule/ability BODY TEXT is diffed by its sibling, sync-faction-text.mjs — that one
// strips wh11ed's enrichment layer (gloss tokens, cross-references, extra bold, bracket
// ability names) off both sides before comparing, so the prose diff stays high-signal instead
// of the all-noise it would be raw. Run both (npm run sync runs them back to back).
//
// For the 5 SM-Chapter factions (deathwatch, black-templars, blood-angels, dark-angels,
// space-wolves): wh11ed's datasheet list already folds in units shared with
// space-marines.js (see sharedIdsFor in data/datasheets/index.js), but appdata's own
// per-chapter bundle only lists that Chapter's OWN publications — units GW considers part
// of the general Adeptus Astartes pool live under appdata's adeptus-astartes.json instead.
// So an "extra in wh11ed" datasheet for a Chapter may legitimately belong to that shared
// pool rather than being wrong — cross-check space-marines vs adeptus-astartes separately
// before treating a Chapter's "extra" list as actionable.
//
// Related false-positive: a "points differ" finding under the base "space-marines" section
// for a handful of shared units (Assault Intercessor Squad, Bladeguard Veteran Squad,
// Captain/Chaplain With Jump Pack, Outrider Squad, Repulsor Executioner, Vanguard Veteran
// Squad With Jump Packs) will persist even after fixing the actual gap. appdata's per-
// datasheet points list is unfiltered by unit_composition_required_faction_keyword, so it
// merges the generic price with every Chapter-specific variant (e.g. Blood Angels pays more
// for Bladeguard Veteran Squad) into one flat set — space-marines.js correctly shows only
// the generic price, the Chapter-specific one lives in that Chapter's own `pointsOverrides`
// export (see blood-angels.js), applied at runtime by loadDatasheets. This script diffs
// space-marines.js as a flat list and has no way to attribute a value to "generic" vs "only
// when this faction keyword applies", so it will keep reporting the merged set as a mismatch
// — check unit_composition_required_faction_keyword by hand before treating this class as a
// real gap (see APPDATA-SYNC-LESSONS.md for the full mechanism).

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { ROOT, APPDATA, SLUG_MAP, norm, looseName, isWeaponType, appdataToMarkup, bodyText, loadJson, loadModule, byNormName, diffByName, diffSet, matchWeapon, combatPatrolNames, loadWh11edDatasheets } from './lib/sync-common.mjs'

// Scalar field maps for statline/weapon-profile comparisons: [wh11ed key, appdata key].
const STAT_FIELDS = [['m', 'M'], ['t', 'T'], ['sv', 'Sv'], ['w', 'W'], ['ld', 'Ld'], ['oc', 'OC']]
const WEAPON_FIELDS = {
  ranged: [['a', 'A'], ['bs', 'BS'], ['s', 'S'], ['ap', 'AP'], ['d', 'D']],
  melee: [['a', 'A'], ['ws', 'WS'], ['s', 'S'], ['ap', 'AP'], ['d', 'D']],
}

async function syncFaction(slug) {
  const appSlug = SLUG_MAP[slug] || slug
  const bundle = await loadJson(path.join(APPDATA, 'factions', `${appSlug}.json`))
  console.log(`\n=== ${slug} (appdata: ${appSlug}) ===`)
  if (!bundle) { console.log('  no appdata bundle found — check SLUG_MAP or spelling'); return }

  // Each faction file's only export is a camelCase binding (`blackTemplars`, `spaceMarines`,
  // ...) that doesn't match the dashed slug — grab whatever the module's one export is.
  const factionMod = await loadModule(path.join(ROOT, 'src/data/factions', `${slug}.js`))
  const en = Object.values(factionMod || {})[0]?.en
  if (!en) { console.log('  no src/data/factions/<slug>.js found'); return }

  const lines = []
  // Stable-id bridge (src/data/sourceIds.json, generated by gen-source-ids.mjs): maps each
  // wh11ed entity to its appdata source UUID. Lets us tell a rename ("same id, new name") from
  // a genuine add/remove after a data_version bump — see the rename block after the datasheet loop.
  const smap = (loadJson(path.join(ROOT, 'src/data/sourceIds.json')) || {})[slug] || {}

  // Drop Combat Patrol content — a separate game mode wh11ed doesn't carry (see helper).
  const cp = combatPatrolNames()
  const appDetachments = (bundle.detachments || []).filter((d) => !cp.detachments.has(norm(d.name)))
  const appDatasheets = (bundle.datasheets || []).filter((d) => !cp.datasheets.has(norm(d.name)))

  // Army rule(s): wh11ed has one combined armyRule; appdata may have several.
  const appArmyNames = (bundle.armyRules || []).map((a) => norm(a.name))
  if (en.armyRule && !appArmyNames.some((n) => (en.armyRule.name || '').toLowerCase().includes(n) || n.includes((en.armyRule.name || '').toLowerCase()))) {
    lines.push(`  ~ army rule "${en.armyRule.name}" doesn't obviously match any appdata army rule (${bundle.armyRules.map((a) => a.name).join(', ') || 'none'}) — check by hand`)
  }

  // Detachments, and within each, stratagems/enhancements.
  lines.push(...diffByName('detachment', en.detachments, appDetachments, (d) => d.name, (d) => d.name, [],
    (d) => (d.rules || []).map((r) => `${r.name}: ${bodyText(r.body)}`).join(' | ')))
  const appDetByName = byNormName(appDetachments, (d) => d.name)
  for (const d of en.detachments || []) {
    const appDet = appDetByName.get(norm(d.name))
    if (!appDet) continue
    const sub = [
      ...diffByName('stratagem', d.stratagems, appDet.stratagems, (s) => s.name, (s) => s.name, [['cp', 'cp']],
        (s) => `${s.cp}CP — ${appdataToMarkup(s.effect)}`),
      ...diffByName('enhancement', d.enhancements, appDet.enhancements, (e) => e.name, (e) => e.name, [['points', 'cost']],
        (e) => `${e.cost ?? 0}pts — ${appdataToMarkup(e.rules)}`),
    ]
    if (sub.length) lines.push(`  in detachment "${d.name}":`, ...sub.map((l) => `  ${l}`))
  }

  // Datasheets. For entirely missing units, a points/keywords pointer is enough — a new
  // datasheet needs full authoring (RU translation included), not a one-line paste.
  const wh11edSheets = await loadWh11edDatasheets(slug)
  const appDsByName = byNormName(appDatasheets, (d) => d.name)
  // A Legends sheet authored from the Faction Pack PDF (`source: 'faction-pack'`, see the hub's
  // `legends-from-pack` skill) is expected to be absent from appdata — the app carries Legends
  // for Orks alone today — so it is not an "extra". The day appdata DOES carry it, that copy is
  // superseded and says so: appdata is the source of truth, the pack was the stand-in.
  const packSheets = wh11edSheets.filter((d) => d.source === 'faction-pack')
  for (const d of packSheets) {
    if (appDsByName.has(norm(d.name))) lines.push(`  ⟲ datasheet "${d.name}" [${d.id}] is now in appdata — retire the faction-pack copy (re-author from appdata, drop \`source\`)`)
  }
  lines.push(...diffByName('datasheet', wh11edSheets.filter((d) => d.source !== 'faction-pack'), appDatasheets, (d) => d.name, (d) => d.name, [],
    (d) => `${(d.points || []).map((p) => `${p.models}=${p.points}pts`).join(', ')} — ${(d.keywords || []).join(', ')}`))
  for (const d of wh11edSheets) {
    const appDs = appDsByName.get(norm(d.name))
    if (!appDs) continue
    // wh11ed's `points[].note` sometimes marks MFM "copy tax" tiers ("1st-2nd" vs "3rd+"
    // costing more for spamming the same unit) — appdata's composition join only exposes
    // the base price, so drop any tier past the first before comparing.
    // appdata's own unit_composition join sometimes yields duplicate rows for the same
    // price (multiple miniature slots in one composition) — de-dupe before comparing.
    // The ordinal can be the whole note ("3rd+") or trail a longer composition
    // description in parens ("3 Wolf Guard Headtakers (3rd+)") — match either.
    const isSurchargeTier = (note) => note && /(^|\()(2nd|3rd|4th|5th)/i.test(note)
    const whPts = [...new Set((d.points || []).filter((p) => !isSurchargeTier(p.note)).map((p) => p.points))].sort((x, y) => x - y)
    const appPts = [...new Set((appDs.points || []).map((p) => p.points))].sort((x, y) => x - y)
    if (whPts.length && appPts.length && JSON.stringify(whPts) !== JSON.stringify(appPts)) {
      lines.push(`  ~ datasheet "${d.name}" points differ: wh11ed=${JSON.stringify(whPts)} appdata=${JSON.stringify(appPts)}`)
    }
    // Only appdata's `type: 'datasheet'` abilities are genuinely unit-specific and map to
    // wh11ed's `abilities` array — `core`/`faction` are Core Rulebook/army-rule references
    // wh11ed keeps as its own `core`/`faction` summary strings, and `wargear` maps to
    // `wargearAbilities`, not `abilities`.
    const whAbilities = new Set((d.abilities || []).map((a) => norm(a.name)))
    const appAbilityByName = byNormName((appDs.abilities || []).filter((a) => a.type === 'datasheet'), (a) => a.name)
    for (const [n, a] of appAbilityByName) {
      if (!whAbilities.has(n)) lines.push(`  + datasheet "${d.name}" missing ability: "${a.name}" — ${appdataToMarkup(a.rules)}`)
    }
    for (const n of whAbilities) if (!appAbilityByName.has(n)) lines.push(`  - datasheet "${d.name}" extra ability (not in appdata): "${n}"`)

    // Compare core+faction as ONE merged set, not two separate fields: wh11ed's `faction`
    // is itself sometimes a comma-joined list (e.g. Aeldari's "Battle Focus, Disparate
    // Paths"), and appdata inconsistently buckets the same ability name as 'core' on some
    // datasheets and 'faction' on others (e.g. "Super-heavy Walker") — diffing per-field
    // would flag that inconsistency as a false difference even when the name set matches.
    const appCoreFaction = (appDs.abilities || []).filter((a) => a.type === 'core' || a.type === 'faction').map((a) => norm(a.name))
    const whCoreFaction = [...(d.core || '').split(','), ...(d.faction || '').split(',')].map((s) => norm(s.trim())).filter(Boolean)
    const missingCF = appCoreFaction.filter((n) => !whCoreFaction.includes(n))
    const extraCF = whCoreFaction.filter((n) => !appCoreFaction.includes(n))
    if (missingCF.length || extraCF.length) {
      lines.push(`  ~ datasheet "${d.name}" core/faction differ: wh11ed=${JSON.stringify([d.core, d.faction].filter(Boolean))} appdata=${JSON.stringify(appCoreFaction)}`)
    }

    // Stats: match wh11ed's profiles[] to appdata's statlines[] by name; if unmatched AND wh11ed
    // collapsed the unit to a single representative profile row (the common squad case — appdata
    // gives one statline per named model even when every model is identical), accept a match
    // against ANY statline whose values agree instead. Only flag when neither path finds one.
    const appStatByName = byNormName(appDs.statlines || [], (s) => s.name)
    for (const p of d.profiles || []) {
      let appStat = appStatByName.get(norm(p.name))
      if (!appStat && d.profiles.length === 1) {
        appStat = (appDs.statlines || []).find((s) => STAT_FIELDS.every(([wf, af]) => String(p[wf] ?? '') === String(s[af] ?? '')))
      }
      if (!appStat) { lines.push(`  ~ datasheet "${d.name}" profile "${p.name}" has no matching appdata statline`); continue }
      for (const [wf, af] of STAT_FIELDS) {
        if (String(p[wf] ?? '') !== String(appStat[af] ?? '')) {
          lines.push(`  ~ datasheet "${d.name}" profile "${p.name}" ${wf.toUpperCase()} differs: wh11ed=${JSON.stringify(p[wf])} appdata=${JSON.stringify(appStat[af])}`)
        }
      }
      // A composite multi-model unit (e.g. a Character with named bodyguard-type models sharing
      // one datasheet) may carry baseSize per PROFILE instead of the single top-level d.baseSize —
      // appdata has no per-statline baseSize field either, only the same top-level string with one
      // "<model name>: <size>" line per component, so find this profile's own line by name.
      if (p.baseSize && appDs.baseSize) {
        const line = appDs.baseSize.split('\n').find((l) => norm(l).includes(norm(p.name)))
        const appSize = line && (line.match(/\d[\d.]*(?:\s*x\s*\d[\d.]*)?\s*mm|hull|unique/i) || [])[0]
        if (appSize && appSize.toLowerCase().replace(/\s+/g, '') !== p.baseSize.toLowerCase().replace(/\s+/g, '')) {
          lines.push(`  ~ datasheet "${d.name}" profile "${p.name}" baseSize differs: wh11ed=${JSON.stringify(p.baseSize)} appdata=${JSON.stringify(appSize)}`)
        }
      }
    }

    // Invulnerable saves: only compared when unambiguous (wh11ed has at most one `inv` value
    // across its profiles, appdata has exactly one invulnerableSaves entry with no miniatureId
    // scoping it to one model of a multi-model unit) — appdata's miniatureId doesn't resolve to a
    // wh11ed profile name without an extra join, so ambiguous cases are silently skipped rather
    // than guessed at.
    const whInv = [...new Set((d.profiles || []).map((p) => p.inv).filter(Boolean))]
    const appInvList = appDs.invulnerableSaves || []
    if (whInv.length <= 1 && appInvList.length === 1 && !appInvList[0].miniatureId) {
      const appInv = appInvList[0].save || appInvList[0].rangedSave
      if ((whInv[0] || null) !== (appInv || null) && (whInv[0] || appInv)) {
        lines.push(`  ~ datasheet "${d.name}" invulnerable save differs: wh11ed=${JSON.stringify(whInv[0] || null)} appdata=${JSON.stringify(appInv || null)}`)
      }
    } else if (whInv.length && !appInvList.length) {
      lines.push(`  ~ datasheet "${d.name}" has an invulnerable save (${whInv.join('/')}) not found in appdata`)
    } else if (!whInv.length && appInvList.length === 1 && !appInvList[0].miniatureId && (appInvList[0].save || appInvList[0].rangedSave)) {
      lines.push(`  + datasheet "${d.name}" missing invulnerable save: appdata has ${appInvList[0].save || `${appInvList[0].rangedSave}/${appInvList[0].meleeSave}`}`)
    }

    // Weapons: resolve each wh11ed ranged[]/melee[] row to its appdata wargear item, id-first via
    // the sourceIds `wg:` bridge (immune to later name drift), falling back to matchWeapon() for
    // rows the bridge doesn't cover yet. Presence and field comparisons share this ONE resolution
    // per row, so they can never disagree about which appdata entry a row corresponds to.
    const appWgById = new Map((appDs.wargear || []).map((w) => [w.id, w]))
    const claimedProfiles = new Set()
    for (const kind of ['ranged', 'melee']) {
      const isRanged = kind === 'ranged'
      for (const w of d[kind] || []) {
        const wgId = smap[`wg:${d.id}:${norm(w.name)}`]
        const item = (wgId && appWgById.get(wgId)) || matchWeapon(w.name, isRanged, appDs.wargear)
        if (!item) { lines.push(`  - datasheet "${d.name}" extra ${kind} weapon (not in appdata): "${w.name}"`); continue }
        const profiles = (item.profiles || []).filter((p) => isWeaponType(p.type, isRanged))
        // A profile's own mode label can be a substring of another's within the same item (e.g.
        // "witchfire" vs "focused witchfire") — endsWith() would match BOTH, so among all
        // candidates take the longest (most specific) match, not the first in array order.
        // The loose pass is the same fallback matchWeapon uses and for the same reason: Drazhar's
        // row ends "– dual blades" where appdata's profile is "(dual blade)", and taking
        // profiles[0] instead silently compared our dual-blade row against the single-blade
        // profile AND left the real one looking unclaimed.
        const pick = (fold) => profiles.filter((p) => fold(w.name).endsWith(fold(p.name)))
          .sort((a, b) => b.name.length - a.name.length)[0]
        const profile = profiles.length <= 1 ? profiles[0]
          : pick(norm) || pick(looseName) || profiles[0]
        if (!profile) continue
        claimedProfiles.add(`${item.id}|${profile.type}|${profile.name}`)
        for (const [wf, af] of WEAPON_FIELDS[kind]) {
          if (String(w[wf] ?? '') !== String(profile[af] ?? '')) {
            lines.push(`  ~ datasheet "${d.name}" weapon "${w.name}" ${wf.toUpperCase()} differs: wh11ed=${JSON.stringify(w[wf])} appdata=${JSON.stringify(profile[af])}`)
          }
        }
        if (isRanged && String(w.range ?? '') !== String(profile.range ?? '')) {
          lines.push(`  ~ datasheet "${d.name}" weapon "${w.name}" range differs: wh11ed=${JSON.stringify(w.range)} appdata=${JSON.stringify(profile.range)}`)
        }
        const whTags = [...(w.tags || [])].map((t) => t.toUpperCase()).sort()
        const appTags = [...(profile.tags || [])].map((t) => t.toUpperCase()).sort()
        if (JSON.stringify(whTags) !== JSON.stringify(appTags)) {
          lines.push(`  ~ datasheet "${d.name}" weapon "${w.name}" tags differ: wh11ed=${JSON.stringify(whTags)} appdata=${JSON.stringify(appTags)}`)
        }
      }
    }
    for (const item of appDs.wargear || []) {
      for (const p of item.profiles || []) {
        if (claimedProfiles.has(`${item.id}|${p.type}|${p.name}`)) continue
        const sameType = item.profiles.filter((pp) => pp.type === p.type)
        const label = sameType.length > 1 ? `${item.name} (${p.name})` : item.name
        lines.push(`  + datasheet "${d.name}" missing ${p.type} weapon: "${label}"`)
      }
    }

    // Keywords: full set diff for every matched datasheet (previously only shown as a text
    // pointer when the whole datasheet was missing). appdata's per-datasheet `factionKeywords` is
    // always empty in this bundle shape (the faction keyword is implied by which faction bundle
    // you're reading, not repeated per-sheet) — comparing it would be 100% noise, so only
    // `keywords[]` is diffed; wh11ed's own `factionKeywords` isn't checked here.
    lines.push(...diffSet(`datasheet "${d.name}" · keyword`, d.keywords || [], appDs.keywords || []))

    // baseSize: exact scalar (both sides are short strings like "32mm") — appdata always spaces
    // out "170 x 109mm", wh11ed always writes "170x109mm" — and for a mixed-base unit (a wargear
    // variant on its own base, e.g. Cthonian Beserks' Mole grenade launcher) appdata spells out
    // "<Model name>: <size>" per line while wh11ed's own convention (see e.g.
    // adeptus-mechanicus.js) is a bare "<size> / <size>" list with no names at all. So extract
    // just the size tokens in order from both sides (ignoring any per-line name prefix) instead
    // of a literal string compare — this also makes the whitespace-only fold below redundant, but
    // subsumes it (a plain "170 x 109mm" line still yields just "170x109mm").
    const foldBaseSize = (s) => (s || '')
      .split(/[\n/]/)
      .map((part) => (part.match(/\d[\d.]*(?:\s*x\s*\d[\d.]*)?\s*mm|hull|unique|large flying base|small flying base/i) || [])[0])
      .filter(Boolean)
      .map((tok) => tok.toLowerCase().replace(/\s+/g, ''))
      .join('/')
    if (d.baseSize && appDs.baseSize && foldBaseSize(d.baseSize) !== foldBaseSize(appDs.baseSize)) {
      lines.push(`  ~ datasheet "${d.name}" baseSize differs: wh11ed=${JSON.stringify(d.baseSize)} appdata=${JSON.stringify(appDs.baseSize)}`)
    }

    // Leader/bodyguards: structural units-list diff (independent of the prose leader.text diffed
    // in sync-faction-text.mjs). NOTE: appdata's leaderOf[] doesn't carry detachment-gating
    // (requiredDetachmentId/excludedDetachmentId only exist in the raw tables/
    // datasheet_bodyguard_group.json, not in this bundle) — a clean match here doesn't confirm any
    // detachment restriction is right, only that the unconditional unit list agrees.
    const appLeaderUnits = (appDs.leaderOf || []).flatMap((l) => l.units || [])
    if (d.leader?.units?.length || appLeaderUnits.length) {
      lines.push(...diffSet(`datasheet "${d.name}" · bodyguard unit`, d.leader?.units || [], appLeaderUnits))
    }
  }

  // Rename detection via the stable-id bridge: for every id-keyed entity we mapped on a prior
  // sync, if the appdata entity with that source UUID now carries a different name, GW renamed it
  // — report it as a rename to update (not the "missing + extra" pair the name-diff would show).
  // Silent today (names agree, that's the point); real value lands on the next data_version bump.
  const appDsById = new Map(appDatasheets.map((d) => [d.id, d]))
  const appDetById = new Map(appDetachments.map((d) => [d.id, d]))
  for (const d of wh11edSheets) {
    const srcId = smap[`ds:${d.id}`]
    if (!srcId) continue
    const appDs = appDsById.get(srcId)
    if (appDs && norm(appDs.name) !== norm(d.name)) lines.push(`  ⟲ datasheet renamed in appdata: wh11ed "${d.name}" [${d.id}] → appdata "${appDs.name}"`)
    // …and the same comparison WITHOUT norm(), because norm() lowercases and so is blind to the
    // one difference that shows up in a heading: 59 units were spelled "Captain In Phobos Armour"
    // against appdata's "Captain in Phobos Armour", and it reached every <h1> and <title> the SEO
    // pass generates while every check here stayed green (found 2026-08-26).
    else if (appDs && appDs.name !== d.name) lines.push(`  ⟲ datasheet name case differs: wh11ed "${d.name}" [${d.id}] → appdata "${appDs.name}"`)
  }
  for (const d of en.detachments || []) {
    const srcId = smap[`det:${d.id || norm(d.name)}`]
    if (!srcId) continue
    const appDet = appDetById.get(srcId)
    if (appDet && norm(appDet.name) !== norm(d.name)) lines.push(`  ⟲ detachment renamed in appdata: wh11ed "${d.name}" → appdata "${appDet.name}"`)
  }

  if (!lines.length) console.log('  no structural differences found')
  else lines.forEach((l) => console.log(l))
}

export async function run(argv = process.argv.slice(2)) {
  let slugs = argv
  if (argv[0] === '--all') {
    slugs = fs.readdirSync(path.join(ROOT, 'src/data/factions'))
      .filter((f) => f.endsWith('.js') && f !== 'index.js')
      .map((f) => f.replace(/\.js$/, ''))
  }
  if (!slugs.length) {
    console.log('Usage: node scripts/sync-appdata.mjs <slug> [<slug> ...] | --all')
    return 1
  }
  for (const slug of slugs) await syncFaction(slug)
  return 0
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) process.exit(await run())
